# Copyright BigchainDB GmbH and BigchainDB contributors
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

version: '2.1'

services:
  bigchaindb-driver:
    depends_on:
      - bigchaindb
    build:
      context: .
      dockerfile: ./src/bigchaindb/compose/bigchaindb_driver/Dockerfile
    volumes:
      - ./src/bigchaindb/docs:/usr/src/app/docs
      - ./src/bigchaindb/tests:/usr/src/app/tests
      - ./src/bigchaindb/bigchaindb_driver:/usr/src/app/bigchaindb_driver
      - ./src/bigchaindb/setup.py:/usr/src/app/setup.py
      - ./src/bigchaindb/tox.ini:/usr/src/app/tox.ini
      - ./src/bigchaindb/htmlcov:/usr/src/app/htmlcov
      - ./src/bigchaindb/coverage.xml:/usr/src/app/coverage.xml
    environment:
      BDB_HOST: bigchaindb
      BIGCHAINDB_DATABASE_BACKEND: mongodb
    command: pytest -v
  mongodb:
    image: mongo:3.6
    ports:
      - "27017"
    command: mongod
  bigchaindb:
    depends_on:
      - mongodb
      - tendermint
    build:
      context: .
      dockerfile: ./src/bigchaindb/compose/bigchaindb_server/Dockerfile
      args:
        branch: master
        backend: localmongodb
    environment:
      BIGCHAINDB_DATABASE_HOST: mongodb
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
      BIGCHAINDB_TENDERMINT_HOST: tendermint
      BIGCHAINDB_TENDERMINT_PORT: 26657
    ports:
      - "9984"
      - "9985"
      - "26658"
    healthcheck:
      test: ["CMD", "bash", "-c", "curl http://bigchaindb:9984 && curl http://tendermint:26657/abci_query"]
      interval: 3s
      timeout: 5s
      retries: 3
    command: bigchaindb -l DEBUG start
    networks:
      - default
      - hospital-bigchaindb
  tendermint:
    image: tendermint/tendermint:0.22.8
    entrypoint: ''
    ports:
      - "26656:26656"
      - "26657:26657"
    command: sh -c "tendermint init && tendermint node --consensus.create_empty_blocks=false --proxy_app=tcp://bigchaindb:26658"
  bdb:
    image: busybox
    depends_on:
      bigchaindb:
        condition: service_healthy
  # Build docs only
  # docker-compose build bdocs
  # docker-compose up -d bdocs
  bdocs:
    depends_on:
      - vdocs
    build:
      context: .
      dockerfile: ./src/bigchaindb/compose/bigchaindb_driver/Dockerfile
    volumes:
      - ./src/bigchaindb/:/usr/src/app/
    command: make -C docs html
  vdocs:
    image: nginx
    ports:
      - '55555:80'
    volumes:
      - ./src/bigchaindb/docs/_build/html:/usr/share/nginx/html

networks:
  hospital-bigchain:
    external:
      name: hrms-hospital-bigchain
