version: '2.2'

services:
  centraldb:
    build:
      context: ./src/centraldb
    environment:
      - GRPC_LISTEN_ADDR=:8080
      - SQL_DSN=centraldb:centraldb@tcp(mysql:3306)/centraldb
    expose:
      - '8080'
    networks:
      - default
      - hospital-centraldb
      - hospital-discovery
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: centraldb
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: centraldb
      MYSQL_PASSWORD: centraldb
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

networks:
  hospital-centraldb:
    external:
      name: hrms-hospital-centraldb
  hospital-discovery:
    external:
      name: hrms-hospital-discovery
