version: '3'

services:
  zookeeper:
    image: zookeeper
    networks:
      - hospital-discovery
    volumes:
      - zk-data:/data

volumes:
  zk-data: {}

networks:
  hospital-discovery:
    external:
      name: hrms-hospital-discovery
