# Docker Compose file for a single hospital's microservice architecture.

version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./build/frontend/Dockerfile
    environment:
      - HOSPITAL_NAME
    ports:
      - '127.0.0.1:${FRONTEND_PORT:-8000}:80'
    depends_on:
      - api_gateway

  api_gateway:
    build:
      context: .
      dockerfile: ./build/nameko/Dockerfile
      args:
        module: api_gateway
    ports:
      - '127.0.0.1:${API_GATEWAY_PORT:-8100}:80'
    healthcheck:
      test: ['CMD', 'curl', '-f', '-s', 'localhost/healthy']
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - default
      - rabbitmq
    depends_on:
      - rabbitmq
      - patient_service
      - physician_service

  patient_service:
    build:
      context: .
      dockerfile: ./build/nameko/Dockerfile
      args:
        module: patient_service
    environment:
      - HOSPITAL_NAME
      - REDIS_HOST=redis
    networks:
      - default
      - rabbitmq
    depends_on:
      - rabbitmq
      - consistent_storage
      - redis

  physician_service:
    build:
      context: .
      dockerfile: ./build/nameko/Dockerfile
      args:
        module: physician_service
    environment:
      - HOSPITAL_NAME
      - REDIS_HOST=redis
    networks:
      - default
      - rabbitmq
    depends_on:
      - rabbitmq
      - consistent_storage
      - redis

  rabbitmq:
    image: rabbitmq:3
    networks:
      - rabbitmq

  consistent_storage:
    env_file: .env
    build:
      context: .
      dockerfile: ./build/consistent_storage/Dockerfile
      args:
        module: consistent_storage
    networks:
      - default
      - rabbitmq
      - hospital-bigchain
    environment:
      - CONSISTENT_STORAGE_BACKEND=${CONSISTENT_STORAGE_BACKEND:-sagas}
      - SAGAS_GRPC_ADDR=sagas:8080

  sagas:
    env_file: .env
    build:
      context: ./src/sagas
    networks:
      - default
      - hospital-sagas
    environment:
      - NUM_PARTITIONS=${SAGAS_NUM_PARTITIONS}
      - TOPIC_NAME=patient_registrations
      - KAFKA_BROKERS=kafka:9092
      - STORAGE_FILE_PATH=/var/lib/sagas/data.json
      - GRPC_LISTEN_ADDR=:8080
    expose:
      - 8080
    volumes:
      - sagas-storage:/var/lib/sagas

  redis:
    image: redis
    volumes:
      - local-storage:/data

volumes:
  local-storage: {}
  sagas-storage: {}

networks:
  rabbitmq: {}
  hospital-sagas:
    external:
      name: hrms-hospital-sagas
  hospital-bigchain:
    external:
      name: hrms-hospital-bigchain
