version: '3'

services:
  centraldb:
    build:
      context: ./src/centraldb
    environment:
      - GRPC_LISTEN_ADDR=:8080
      - SQL_DSN=centraldb:centraldb@tcp(mysql:3306)/centraldb
    expose:
      - '8080'
    networks:
      - default
      - hospital-centraldb
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: centraldb
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: centraldb
      MYSQL_PASSWORD: centraldb

networks:
  hospital-centraldb:
    external:
      name: hrms-hospital-centraldb
