// Code generated by protoc-gen-go. DO NOT EDIT.
// source: discovery.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{0}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Hospitals            []*ListResponse_Hospital `protobuf:"bytes,1,rep,name=hospitals,proto3" json:"hospitals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{1}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetHospitals() []*ListResponse_Hospital {
	if m != nil {
		return m.Hospitals
	}
	return nil
}

type ListResponse_Hospital struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RegisteredTime       int64    `protobuf:"varint,3,opt,name=registeredTime,proto3" json:"registeredTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse_Hospital) Reset()         { *m = ListResponse_Hospital{} }
func (m *ListResponse_Hospital) String() string { return proto.CompactTextString(m) }
func (*ListResponse_Hospital) ProtoMessage()    {}
func (*ListResponse_Hospital) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{1, 0}
}

func (m *ListResponse_Hospital) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse_Hospital.Unmarshal(m, b)
}
func (m *ListResponse_Hospital) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse_Hospital.Marshal(b, m, deterministic)
}
func (m *ListResponse_Hospital) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse_Hospital.Merge(m, src)
}
func (m *ListResponse_Hospital) XXX_Size() int {
	return xxx_messageInfo_ListResponse_Hospital.Size(m)
}
func (m *ListResponse_Hospital) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse_Hospital.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse_Hospital proto.InternalMessageInfo

func (m *ListResponse_Hospital) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ListResponse_Hospital) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListResponse_Hospital) GetRegisteredTime() int64 {
	if m != nil {
		return m.RegisteredTime
	}
	return 0
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "ListRequest")
	proto.RegisterType((*ListResponse)(nil), "ListResponse")
	proto.RegisterType((*ListResponse_Hospital)(nil), "ListResponse.Hospital")
}

func init() {
	proto.RegisterFile("discovery.proto", fileDescriptor_1e7ff60feb39c8d0)
}

var fileDescriptor_1e7ff60feb39c8d0 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xc9, 0x2c, 0x4e,
	0xce, 0x2f, 0x4b, 0x2d, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xe2, 0xe5, 0xe2, 0xf6,
	0xc9, 0x2c, 0x2e, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0x9a, 0xc3, 0xc8, 0xc5, 0x03,
	0xe1, 0x17, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x99, 0x70, 0x71, 0x66, 0xe4, 0x17, 0x17, 0x64,
	0x96, 0x24, 0xe6, 0x14, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0x89, 0xe9, 0x21, 0xab, 0xd0,
	0xf3, 0x80, 0x4a, 0x07, 0x21, 0x14, 0x4a, 0x85, 0x71, 0x71, 0xc0, 0x84, 0x85, 0xf8, 0xb8, 0x98,
	0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x98, 0x32, 0x53, 0x84, 0x84, 0xb8, 0x58,
	0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0xc0, 0x22, 0x60, 0xb6, 0x90, 0x1a, 0x17, 0x5f, 0x51, 0x6a,
	0x7a, 0x66, 0x71, 0x49, 0x6a, 0x51, 0x6a, 0x4a, 0x48, 0x66, 0x6e, 0xaa, 0x04, 0xb3, 0x02, 0xa3,
	0x06, 0x73, 0x10, 0x9a, 0xa8, 0x91, 0x33, 0x97, 0x20, 0xcc, 0x5c, 0x17, 0x98, 0x47, 0x84, 0xf4,
	0xb8, 0x78, 0x41, 0x0e, 0x82, 0x49, 0x14, 0x0b, 0xf1, 0xe8, 0x21, 0x79, 0x49, 0x8a, 0x17, 0xc5,
	0xb9, 0x4a, 0x0c, 0x4e, 0x6c, 0x51, 0x2c, 0xb9, 0x89, 0x99, 0x79, 0x49, 0x6c, 0xe0, 0x10, 0x30,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x01, 0xf9, 0xff, 0xf6, 0x14, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HospitalDiscoveryClient is the client API for HospitalDiscovery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HospitalDiscoveryClient interface {
	ListHospitals(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type hospitalDiscoveryClient struct {
	cc grpc.ClientConnInterface
}

func NewHospitalDiscoveryClient(cc grpc.ClientConnInterface) HospitalDiscoveryClient {
	return &hospitalDiscoveryClient{cc}
}

func (c *hospitalDiscoveryClient) ListHospitals(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/HospitalDiscovery/ListHospitals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HospitalDiscoveryServer is the server API for HospitalDiscovery service.
type HospitalDiscoveryServer interface {
	ListHospitals(context.Context, *ListRequest) (*ListResponse, error)
}

// UnimplementedHospitalDiscoveryServer can be embedded to have forward compatible implementations.
type UnimplementedHospitalDiscoveryServer struct {
}

func (*UnimplementedHospitalDiscoveryServer) ListHospitals(ctx context.Context, req *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHospitals not implemented")
}

func RegisterHospitalDiscoveryServer(s *grpc.Server, srv HospitalDiscoveryServer) {
	s.RegisterService(&_HospitalDiscovery_serviceDesc, srv)
}

func _HospitalDiscovery_ListHospitals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HospitalDiscoveryServer).ListHospitals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HospitalDiscovery/ListHospitals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HospitalDiscoveryServer).ListHospitals(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HospitalDiscovery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HospitalDiscovery",
	HandlerType: (*HospitalDiscoveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListHospitals",
			Handler:    _HospitalDiscovery_ListHospitals_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discovery.proto",
}
