// Code generated by protoc-gen-go. DO NOT EDIT.
// source: discovery.proto

package discovery

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Hospital struct {
	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RegisteredTime int64  `protobuf:"varint,3,opt,name=registeredTime,proto3" json:"registeredTime,omitempty"`
	GatewayAddr    string `protobuf:"bytes,4,opt,name=gatewayAddr,proto3" json:"gatewayAddr,omitempty"`
	PublicKey      []byte `protobuf:"bytes,5,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	// communication
	ConsistentStorageAddr string          `protobuf:"bytes,6,opt,name=consistentStorageAddr,proto3" json:"consistentStorageAddr,omitempty"`
	PublicKeys            []*DiscoveryKey `protobuf:"bytes,7,rep,name=publicKeys,proto3" json:"publicKeys,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}        `json:"-"`
	XXX_unrecognized      []byte          `json:"-"`
	XXX_sizecache         int32           `json:"-"`
}

func (m *Hospital) Reset()         { *m = Hospital{} }
func (m *Hospital) String() string { return proto.CompactTextString(m) }
func (*Hospital) ProtoMessage()    {}
func (*Hospital) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{0}
}

func (m *Hospital) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hospital.Unmarshal(m, b)
}
func (m *Hospital) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hospital.Marshal(b, m, deterministic)
}
func (m *Hospital) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hospital.Merge(m, src)
}
func (m *Hospital) XXX_Size() int {
	return xxx_messageInfo_Hospital.Size(m)
}
func (m *Hospital) XXX_DiscardUnknown() {
	xxx_messageInfo_Hospital.DiscardUnknown(m)
}

var xxx_messageInfo_Hospital proto.InternalMessageInfo

func (m *Hospital) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Hospital) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Hospital) GetRegisteredTime() int64 {
	if m != nil {
		return m.RegisteredTime
	}
	return 0
}

func (m *Hospital) GetGatewayAddr() string {
	if m != nil {
		return m.GatewayAddr
	}
	return ""
}

func (m *Hospital) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Hospital) GetConsistentStorageAddr() string {
	if m != nil {
		return m.ConsistentStorageAddr
	}
	return ""
}

func (m *Hospital) GetPublicKeys() []*DiscoveryKey {
	if m != nil {
		return m.PublicKeys
	}
	return nil
}

type InfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoRequest) Reset()         { *m = InfoRequest{} }
func (m *InfoRequest) String() string { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()    {}
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{1}
}

func (m *InfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRequest.Unmarshal(m, b)
}
func (m *InfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRequest.Marshal(b, m, deterministic)
}
func (m *InfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRequest.Merge(m, src)
}
func (m *InfoRequest) XXX_Size() int {
	return xxx_messageInfo_InfoRequest.Size(m)
}
func (m *InfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRequest proto.InternalMessageInfo

type InfoResponse struct {
	RegisteredTime       int64    `protobuf:"varint,1,opt,name=registeredTime,proto3" json:"registeredTime,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PrivateKey           []byte   `protobuf:"bytes,4,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoResponse) Reset()         { *m = InfoResponse{} }
func (m *InfoResponse) String() string { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()    {}
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{2}
}

func (m *InfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResponse.Unmarshal(m, b)
}
func (m *InfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResponse.Marshal(b, m, deterministic)
}
func (m *InfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResponse.Merge(m, src)
}
func (m *InfoResponse) XXX_Size() int {
	return xxx_messageInfo_InfoResponse.Size(m)
}
func (m *InfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResponse proto.InternalMessageInfo

func (m *InfoResponse) GetRegisteredTime() int64 {
	if m != nil {
		return m.RegisteredTime
	}
	return 0
}

func (m *InfoResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InfoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InfoResponse) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{3}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Hospitals            []*Hospital `protobuf:"bytes,1,rep,name=hospitals,proto3" json:"hospitals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{4}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetHospitals() []*Hospital {
	if m != nil {
		return m.Hospitals
	}
	return nil
}

type DiscoveryKey struct {
	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value  []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Public bool   `protobuf:"varint,3,opt,name=public,proto3" json:"public,omitempty"`
	// (should be false for asymmetric)
	Scheme               string   `protobuf:"bytes,4,opt,name=scheme,proto3" json:"scheme,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoveryKey) Reset()         { *m = DiscoveryKey{} }
func (m *DiscoveryKey) String() string { return proto.CompactTextString(m) }
func (*DiscoveryKey) ProtoMessage()    {}
func (*DiscoveryKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{5}
}

func (m *DiscoveryKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoveryKey.Unmarshal(m, b)
}
func (m *DiscoveryKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoveryKey.Marshal(b, m, deterministic)
}
func (m *DiscoveryKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoveryKey.Merge(m, src)
}
func (m *DiscoveryKey) XXX_Size() int {
	return xxx_messageInfo_DiscoveryKey.Size(m)
}
func (m *DiscoveryKey) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoveryKey.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoveryKey proto.InternalMessageInfo

func (m *DiscoveryKey) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DiscoveryKey) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *DiscoveryKey) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

func (m *DiscoveryKey) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

type GetKeyRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Public               bool     `protobuf:"varint,2,opt,name=public,proto3" json:"public,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKeyRequest) Reset()         { *m = GetKeyRequest{} }
func (m *GetKeyRequest) String() string { return proto.CompactTextString(m) }
func (*GetKeyRequest) ProtoMessage()    {}
func (*GetKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{6}
}

func (m *GetKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKeyRequest.Unmarshal(m, b)
}
func (m *GetKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKeyRequest.Marshal(b, m, deterministic)
}
func (m *GetKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKeyRequest.Merge(m, src)
}
func (m *GetKeyRequest) XXX_Size() int {
	return xxx_messageInfo_GetKeyRequest.Size(m)
}
func (m *GetKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetKeyRequest proto.InternalMessageInfo

func (m *GetKeyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetKeyRequest) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

type GetKeyResponse struct {
	Found                bool          `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Key                  *DiscoveryKey `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetKeyResponse) Reset()         { *m = GetKeyResponse{} }
func (m *GetKeyResponse) String() string { return proto.CompactTextString(m) }
func (*GetKeyResponse) ProtoMessage()    {}
func (*GetKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{7}
}

func (m *GetKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKeyResponse.Unmarshal(m, b)
}
func (m *GetKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKeyResponse.Marshal(b, m, deterministic)
}
func (m *GetKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKeyResponse.Merge(m, src)
}
func (m *GetKeyResponse) XXX_Size() int {
	return xxx_messageInfo_GetKeyResponse.Size(m)
}
func (m *GetKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetKeyResponse proto.InternalMessageInfo

func (m *GetKeyResponse) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

func (m *GetKeyResponse) GetKey() *DiscoveryKey {
	if m != nil {
		return m.Key
	}
	return nil
}

type PutKeyRequest struct {
	Key                  *DiscoveryKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PutKeyRequest) Reset()         { *m = PutKeyRequest{} }
func (m *PutKeyRequest) String() string { return proto.CompactTextString(m) }
func (*PutKeyRequest) ProtoMessage()    {}
func (*PutKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{8}
}

func (m *PutKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutKeyRequest.Unmarshal(m, b)
}
func (m *PutKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutKeyRequest.Marshal(b, m, deterministic)
}
func (m *PutKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutKeyRequest.Merge(m, src)
}
func (m *PutKeyRequest) XXX_Size() int {
	return xxx_messageInfo_PutKeyRequest.Size(m)
}
func (m *PutKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutKeyRequest proto.InternalMessageInfo

func (m *PutKeyRequest) GetKey() *DiscoveryKey {
	if m != nil {
		return m.Key
	}
	return nil
}

type PutKeyResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutKeyResponse) Reset()         { *m = PutKeyResponse{} }
func (m *PutKeyResponse) String() string { return proto.CompactTextString(m) }
func (*PutKeyResponse) ProtoMessage()    {}
func (*PutKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{9}
}

func (m *PutKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutKeyResponse.Unmarshal(m, b)
}
func (m *PutKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutKeyResponse.Marshal(b, m, deterministic)
}
func (m *PutKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutKeyResponse.Merge(m, src)
}
func (m *PutKeyResponse) XXX_Size() int {
	return xxx_messageInfo_PutKeyResponse.Size(m)
}
func (m *PutKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutKeyResponse proto.InternalMessageInfo

func (m *PutKeyResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *PutKeyResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Hospital)(nil), "Hospital")
	proto.RegisterType((*InfoRequest)(nil), "InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "InfoResponse")
	proto.RegisterType((*ListRequest)(nil), "ListRequest")
	proto.RegisterType((*ListResponse)(nil), "ListResponse")
	proto.RegisterType((*DiscoveryKey)(nil), "DiscoveryKey")
	proto.RegisterType((*GetKeyRequest)(nil), "GetKeyRequest")
	proto.RegisterType((*GetKeyResponse)(nil), "GetKeyResponse")
	proto.RegisterType((*PutKeyRequest)(nil), "PutKeyRequest")
	proto.RegisterType((*PutKeyResponse)(nil), "PutKeyResponse")
}

func init() {
	proto.RegisterFile("discovery.proto", fileDescriptor_1e7ff60feb39c8d0)
}

var fileDescriptor_1e7ff60feb39c8d0 = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xae, 0xd3, 0x9f, 0x6d, 0xa7, 0x49, 0x2a, 0xac, 0x05, 0x45, 0x15, 0x82, 0xc8, 0x07, 0x88,
	0x84, 0xb0, 0xd0, 0x82, 0xe0, 0xc0, 0x09, 0x84, 0x54, 0xd0, 0x72, 0x40, 0x81, 0x13, 0xb7, 0x6c,
	0xe3, 0x6d, 0xa3, 0xb6, 0x71, 0xb0, 0x9d, 0xa2, 0xf0, 0x82, 0x3c, 0x14, 0x17, 0x14, 0xdb, 0x69,
	0x5d, 0xb6, 0xdc, 0x32, 0xe3, 0xcc, 0xe7, 0xef, 0x67, 0x64, 0x98, 0xe5, 0x85, 0x5c, 0xf2, 0x3d,
	0x13, 0x0d, 0xad, 0x04, 0x57, 0x9c, 0xfc, 0x41, 0x30, 0xfe, 0xc8, 0x65, 0x55, 0xa8, 0x6c, 0x8b,
	0x43, 0xf0, 0x8a, 0x3c, 0x42, 0x31, 0x4a, 0x26, 0xa9, 0x57, 0xe4, 0x18, 0xc3, 0xa0, 0xcc, 0x76,
	0x2c, 0xf2, 0x74, 0x47, 0x7f, 0xe3, 0x27, 0x10, 0x0a, 0xb6, 0x2a, 0xa4, 0x62, 0x82, 0xe5, 0xdf,
	0x8a, 0x1d, 0x8b, 0xfa, 0x31, 0x4a, 0xfa, 0xe9, 0x3f, 0x5d, 0x1c, 0xc3, 0x74, 0x95, 0x29, 0xf6,
	0x33, 0x6b, 0xde, 0xe5, 0xb9, 0x88, 0x06, 0x1a, 0xc2, 0x6d, 0xe1, 0x87, 0x30, 0xa9, 0xea, 0x9b,
	0x6d, 0xb1, 0xbc, 0x66, 0x4d, 0x34, 0x8c, 0x51, 0xe2, 0xa7, 0xc7, 0x06, 0x7e, 0x05, 0xf7, 0x97,
	0xbc, 0x94, 0x2d, 0x64, 0xa9, 0xbe, 0x2a, 0x2e, 0xb2, 0x15, 0xd3, 0x48, 0x23, 0x8d, 0x74, 0xfe,
	0x10, 0x3f, 0x07, 0x38, 0x40, 0xc8, 0xe8, 0x22, 0xee, 0x27, 0xd3, 0xab, 0x80, 0x7e, 0xe8, 0x44,
	0x5f, 0xb3, 0x26, 0x75, 0x7e, 0x20, 0x01, 0x4c, 0x3f, 0x95, 0xb7, 0x3c, 0x65, 0x3f, 0x6a, 0x26,
	0x15, 0xf9, 0x05, 0xbe, 0x29, 0x65, 0xc5, 0x4b, 0x79, 0x4e, 0x2b, 0x3a, 0xab, 0xd5, 0xf8, 0xe6,
	0xdd, 0xf1, 0xad, 0xef, 0xf8, 0xf6, 0x08, 0xa0, 0x12, 0xc5, 0x3e, 0x53, 0xac, 0x95, 0x3b, 0xd0,
	0x72, 0x9d, 0x4e, 0x4b, 0xe5, 0x73, 0x21, 0x55, 0x47, 0xe5, 0x0d, 0xf8, 0xa6, 0xb4, 0x54, 0x9e,
	0xc2, 0x64, 0x6d, 0x63, 0x92, 0x11, 0xd2, 0xba, 0x26, 0xb4, 0x0b, 0x2e, 0x3d, 0x9e, 0x91, 0x35,
	0xf8, 0xae, 0xdc, 0x03, 0x17, 0xe4, 0x70, 0xb9, 0x84, 0xe1, 0x3e, 0xdb, 0xd6, 0x26, 0x58, 0x3f,
	0x35, 0x05, 0x7e, 0x00, 0x23, 0x63, 0x8d, 0xe6, 0x3d, 0x4e, 0x6d, 0xd5, 0xf6, 0xe5, 0x72, 0xcd,
	0x76, 0xcc, 0x86, 0x68, 0x2b, 0xf2, 0x16, 0x82, 0x05, 0x53, 0xad, 0xa5, 0x86, 0xf3, 0xd9, 0xab,
	0x8e, 0xa0, 0x9e, 0x0b, 0x4a, 0x16, 0x10, 0x76, 0xc3, 0x56, 0xe1, 0x25, 0x0c, 0x6f, 0x79, 0x5d,
	0x9a, 0xfd, 0x1b, 0xa7, 0xa6, 0xc0, 0x8f, 0xa1, 0xbf, 0x61, 0x8d, 0x1e, 0xbe, 0x93, 0x64, 0x7b,
	0x42, 0x5e, 0x40, 0xf0, 0xa5, 0x76, 0x59, 0xd8, 0x09, 0xf4, 0xdf, 0x89, 0xd7, 0x10, 0x76, 0x13,
	0xf6, 0xea, 0x10, 0x3c, 0xbe, 0xb1, 0xf7, 0x7a, 0x7c, 0xd3, 0x52, 0x61, 0x42, 0x70, 0x61, 0x23,
	0x35, 0xc5, 0xd5, 0x6f, 0x04, 0xf7, 0x3a, 0xc7, 0x0f, 0xa8, 0x38, 0x81, 0x8b, 0x05, 0x53, 0xed,
	0xda, 0x60, 0x9f, 0x3a, 0xcb, 0x34, 0x0f, 0xa8, 0xbb, 0x4b, 0xa4, 0x87, 0x29, 0x04, 0x6d, 0xa4,
	0x1d, 0x84, 0xc4, 0x3e, 0x75, 0x12, 0x9f, 0x07, 0xd4, 0x0d, 0x9c, 0xf4, 0xf0, 0x33, 0x18, 0x19,
	0x8b, 0x70, 0x48, 0x4f, 0x8c, 0x9e, 0xcf, 0xe8, 0xa9, 0x77, 0xe6, 0x67, 0x23, 0x0a, 0x87, 0xf4,
	0xc4, 0x8f, 0xf9, 0x8c, 0x9e, 0xaa, 0x25, 0xbd, 0xf7, 0xd3, 0xef, 0x93, 0xc3, 0x3b, 0x70, 0x33,
	0xd2, 0x0f, 0xc1, 0xcb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83, 0x55, 0x62, 0x2d, 0x1b, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HospitalDiscoveryClient is the client API for HospitalDiscovery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HospitalDiscoveryClient interface {
	GetInfo(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	ListHospitals(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyResponse, error)
	PutKey(ctx context.Context, in *PutKeyRequest, opts ...grpc.CallOption) (*PutKeyResponse, error)
}

type hospitalDiscoveryClient struct {
	cc grpc.ClientConnInterface
}

func NewHospitalDiscoveryClient(cc grpc.ClientConnInterface) HospitalDiscoveryClient {
	return &hospitalDiscoveryClient{cc}
}

func (c *hospitalDiscoveryClient) GetInfo(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/HospitalDiscovery/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hospitalDiscoveryClient) ListHospitals(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/HospitalDiscovery/ListHospitals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hospitalDiscoveryClient) GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyResponse, error) {
	out := new(GetKeyResponse)
	err := c.cc.Invoke(ctx, "/HospitalDiscovery/GetKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hospitalDiscoveryClient) PutKey(ctx context.Context, in *PutKeyRequest, opts ...grpc.CallOption) (*PutKeyResponse, error) {
	out := new(PutKeyResponse)
	err := c.cc.Invoke(ctx, "/HospitalDiscovery/PutKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HospitalDiscoveryServer is the server API for HospitalDiscovery service.
type HospitalDiscoveryServer interface {
	GetInfo(context.Context, *InfoRequest) (*InfoResponse, error)
	ListHospitals(context.Context, *ListRequest) (*ListResponse, error)
	GetKey(context.Context, *GetKeyRequest) (*GetKeyResponse, error)
	PutKey(context.Context, *PutKeyRequest) (*PutKeyResponse, error)
}

// UnimplementedHospitalDiscoveryServer can be embedded to have forward compatible implementations.
type UnimplementedHospitalDiscoveryServer struct {
}

func (*UnimplementedHospitalDiscoveryServer) GetInfo(ctx context.Context, req *InfoRequest) (*InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (*UnimplementedHospitalDiscoveryServer) ListHospitals(ctx context.Context, req *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHospitals not implemented")
}
func (*UnimplementedHospitalDiscoveryServer) GetKey(ctx context.Context, req *GetKeyRequest) (*GetKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKey not implemented")
}
func (*UnimplementedHospitalDiscoveryServer) PutKey(ctx context.Context, req *PutKeyRequest) (*PutKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutKey not implemented")
}

func RegisterHospitalDiscoveryServer(s *grpc.Server, srv HospitalDiscoveryServer) {
	s.RegisterService(&_HospitalDiscovery_serviceDesc, srv)
}

func _HospitalDiscovery_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HospitalDiscoveryServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HospitalDiscovery/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HospitalDiscoveryServer).GetInfo(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HospitalDiscovery_ListHospitals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HospitalDiscoveryServer).ListHospitals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HospitalDiscovery/ListHospitals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HospitalDiscoveryServer).ListHospitals(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HospitalDiscovery_GetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HospitalDiscoveryServer).GetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HospitalDiscovery/GetKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HospitalDiscoveryServer).GetKey(ctx, req.(*GetKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HospitalDiscovery_PutKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HospitalDiscoveryServer).PutKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HospitalDiscovery/PutKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HospitalDiscoveryServer).PutKey(ctx, req.(*PutKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HospitalDiscovery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HospitalDiscovery",
	HandlerType: (*HospitalDiscoveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _HospitalDiscovery_GetInfo_Handler,
		},
		{
			MethodName: "ListHospitals",
			Handler:    _HospitalDiscovery_ListHospitals_Handler,
		},
		{
			MethodName: "GetKey",
			Handler:    _HospitalDiscovery_GetKey_Handler,
		},
		{
			MethodName: "PutKey",
			Handler:    _HospitalDiscovery_PutKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discovery.proto",
}
