# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import consistent_storage_pb2 as consistent__storage__pb2


class CentralConsistentStorageStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Request = channel.unary_unary(
                '/CentralConsistentStorage/Request',
                request_serializer=consistent__storage__pb2.WrappedRequest.SerializeToString,
                response_deserializer=consistent__storage__pb2.WrappedResponse.FromString,
                )


class CentralConsistentStorageServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Request(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CentralConsistentStorageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Request': grpc.unary_unary_rpc_method_handler(
                    servicer.Request,
                    request_deserializer=consistent__storage__pb2.WrappedRequest.FromString,
                    response_serializer=consistent__storage__pb2.WrappedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CentralConsistentStorage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CentralConsistentStorage(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CentralConsistentStorage/Request',
            consistent__storage__pb2.WrappedRequest.SerializeToString,
            consistent__storage__pb2.WrappedResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class ConsistentStorageStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/ConsistentStorage/Get',
                request_serializer=consistent__storage__pb2.GetRequest.SerializeToString,
                response_deserializer=consistent__storage__pb2.GetResponse.FromString,
                )
        self.Put = channel.unary_unary(
                '/ConsistentStorage/Put',
                request_serializer=consistent__storage__pb2.PutRequest.SerializeToString,
                response_deserializer=consistent__storage__pb2.PutResponse.FromString,
                )
        self.Remove = channel.unary_unary(
                '/ConsistentStorage/Remove',
                request_serializer=consistent__storage__pb2.RemoveRequest.SerializeToString,
                response_deserializer=consistent__storage__pb2.RemoveResponse.FromString,
                )
        self.Transfer = channel.unary_unary(
                '/ConsistentStorage/Transfer',
                request_serializer=consistent__storage__pb2.TransferRequest.SerializeToString,
                response_deserializer=consistent__storage__pb2.TransferResponse.FromString,
                )


class ConsistentStorageServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transfer(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsistentStorageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=consistent__storage__pb2.GetRequest.FromString,
                    response_serializer=consistent__storage__pb2.GetResponse.SerializeToString,
            ),
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=consistent__storage__pb2.PutRequest.FromString,
                    response_serializer=consistent__storage__pb2.PutResponse.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=consistent__storage__pb2.RemoveRequest.FromString,
                    response_serializer=consistent__storage__pb2.RemoveResponse.SerializeToString,
            ),
            'Transfer': grpc.unary_unary_rpc_method_handler(
                    servicer.Transfer,
                    request_deserializer=consistent__storage__pb2.TransferRequest.FromString,
                    response_serializer=consistent__storage__pb2.TransferResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ConsistentStorage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConsistentStorage(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ConsistentStorage/Get',
            consistent__storage__pb2.GetRequest.SerializeToString,
            consistent__storage__pb2.GetResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ConsistentStorage/Put',
            consistent__storage__pb2.PutRequest.SerializeToString,
            consistent__storage__pb2.PutResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ConsistentStorage/Remove',
            consistent__storage__pb2.RemoveRequest.SerializeToString,
            consistent__storage__pb2.RemoveResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Transfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ConsistentStorage/Transfer',
            consistent__storage__pb2.TransferRequest.SerializeToString,
            consistent__storage__pb2.TransferResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
