// Code generated by protoc-gen-go. DO NOT EDIT.
// source: discovery.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Hospital struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RegisteredTime       int64    `protobuf:"varint,3,opt,name=registeredTime,proto3" json:"registeredTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hospital) Reset()         { *m = Hospital{} }
func (m *Hospital) String() string { return proto.CompactTextString(m) }
func (*Hospital) ProtoMessage()    {}
func (*Hospital) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{0}
}

func (m *Hospital) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hospital.Unmarshal(m, b)
}
func (m *Hospital) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hospital.Marshal(b, m, deterministic)
}
func (m *Hospital) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hospital.Merge(m, src)
}
func (m *Hospital) XXX_Size() int {
	return xxx_messageInfo_Hospital.Size(m)
}
func (m *Hospital) XXX_DiscardUnknown() {
	xxx_messageInfo_Hospital.DiscardUnknown(m)
}

var xxx_messageInfo_Hospital proto.InternalMessageInfo

func (m *Hospital) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Hospital) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Hospital) GetRegisteredTime() int64 {
	if m != nil {
		return m.RegisteredTime
	}
	return 0
}

type InfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoRequest) Reset()         { *m = InfoRequest{} }
func (m *InfoRequest) String() string { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()    {}
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{1}
}

func (m *InfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRequest.Unmarshal(m, b)
}
func (m *InfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRequest.Marshal(b, m, deterministic)
}
func (m *InfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRequest.Merge(m, src)
}
func (m *InfoRequest) XXX_Size() int {
	return xxx_messageInfo_InfoRequest.Size(m)
}
func (m *InfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRequest proto.InternalMessageInfo

type InfoResponse struct {
	Hospital             *Hospital `protobuf:"bytes,1,opt,name=hospital,proto3" json:"hospital,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *InfoResponse) Reset()         { *m = InfoResponse{} }
func (m *InfoResponse) String() string { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()    {}
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{2}
}

func (m *InfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResponse.Unmarshal(m, b)
}
func (m *InfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResponse.Marshal(b, m, deterministic)
}
func (m *InfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResponse.Merge(m, src)
}
func (m *InfoResponse) XXX_Size() int {
	return xxx_messageInfo_InfoResponse.Size(m)
}
func (m *InfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResponse proto.InternalMessageInfo

func (m *InfoResponse) GetHospital() *Hospital {
	if m != nil {
		return m.Hospital
	}
	return nil
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{3}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Hospitals            []*Hospital `protobuf:"bytes,1,rep,name=hospitals,proto3" json:"hospitals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{4}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetHospitals() []*Hospital {
	if m != nil {
		return m.Hospitals
	}
	return nil
}

func init() {
	proto.RegisterType((*Hospital)(nil), "Hospital")
	proto.RegisterType((*InfoRequest)(nil), "InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "InfoResponse")
	proto.RegisterType((*ListRequest)(nil), "ListRequest")
	proto.RegisterType((*ListResponse)(nil), "ListResponse")
}

func init() {
	proto.RegisterFile("discovery.proto", fileDescriptor_1e7ff60feb39c8d0)
}

var fileDescriptor_1e7ff60feb39c8d0 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x9b, 0xa4, 0xd4, 0x66, 0x9a, 0x54, 0x9c, 0x53, 0xe8, 0x29, 0x2c, 0xa8, 0x39, 0xed,
	0xa1, 0x22, 0xde, 0x45, 0x50, 0xc1, 0x53, 0x10, 0x0f, 0xde, 0xa2, 0x19, 0x75, 0xc0, 0x64, 0x63,
	0x66, 0x15, 0xfc, 0xf7, 0x92, 0x34, 0xab, 0x6b, 0x6f, 0x3b, 0x6f, 0x96, 0xef, 0x7d, 0x0c, 0x1c,
	0xd6, 0x2c, 0xcf, 0xe6, 0x8b, 0xfa, 0x6f, 0xdd, 0xf5, 0xc6, 0x1a, 0xf5, 0x00, 0xcb, 0x1b, 0x23,
	0x1d, 0xdb, 0xea, 0x1d, 0xd7, 0x10, 0x72, 0x9d, 0x05, 0x79, 0x50, 0xc4, 0x65, 0xc8, 0x35, 0x22,
	0xcc, 0xdb, 0xaa, 0xa1, 0x2c, 0x1c, 0x93, 0xf1, 0x8d, 0x27, 0xb0, 0xee, 0xe9, 0x95, 0xc5, 0x52,
	0x4f, 0xf5, 0x3d, 0x37, 0x94, 0x45, 0x79, 0x50, 0x44, 0xe5, 0x5e, 0xaa, 0x52, 0x58, 0xdd, 0xb6,
	0x2f, 0xa6, 0xa4, 0x8f, 0x4f, 0x12, 0xab, 0xce, 0x21, 0xd9, 0x8d, 0xd2, 0x99, 0x56, 0x08, 0x8f,
	0x61, 0xf9, 0x36, 0xd5, 0x8e, 0x85, 0xab, 0x6d, 0xac, 0x9d, 0x47, 0xf9, 0xbb, 0x1a, 0x28, 0x77,
	0x2c, 0xd6, 0x51, 0x2e, 0x20, 0xd9, 0x8d, 0x13, 0xe5, 0x14, 0x62, 0xf7, 0x55, 0xb2, 0x20, 0x8f,
	0xfe, 0x63, 0xfe, 0x76, 0xdb, 0x06, 0x8e, 0x5c, 0x7c, 0xe5, 0x0e, 0x80, 0x05, 0x1c, 0x5c, 0x93,
	0x1d, 0xb4, 0x30, 0xd1, 0x9e, 0xec, 0x26, 0xd5, 0xbe, 0xab, 0x9a, 0xa1, 0x86, 0x74, 0xe8, 0x75,
	0x08, 0xc1, 0x44, 0x7b, 0x5a, 0x9b, 0x54, 0xfb, 0x56, 0x6a, 0x76, 0xb9, 0x78, 0x9c, 0x37, 0x15,
	0xb7, 0x4f, 0x8b, 0xf1, 0xc6, 0x67, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x23, 0xde, 0xf5,
	0x76, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HospitalDiscoveryClient is the client API for HospitalDiscovery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HospitalDiscoveryClient interface {
	GetInfo(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	ListHospitals(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type hospitalDiscoveryClient struct {
	cc grpc.ClientConnInterface
}

func NewHospitalDiscoveryClient(cc grpc.ClientConnInterface) HospitalDiscoveryClient {
	return &hospitalDiscoveryClient{cc}
}

func (c *hospitalDiscoveryClient) GetInfo(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/HospitalDiscovery/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hospitalDiscoveryClient) ListHospitals(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/HospitalDiscovery/ListHospitals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HospitalDiscoveryServer is the server API for HospitalDiscovery service.
type HospitalDiscoveryServer interface {
	GetInfo(context.Context, *InfoRequest) (*InfoResponse, error)
	ListHospitals(context.Context, *ListRequest) (*ListResponse, error)
}

// UnimplementedHospitalDiscoveryServer can be embedded to have forward compatible implementations.
type UnimplementedHospitalDiscoveryServer struct {
}

func (*UnimplementedHospitalDiscoveryServer) GetInfo(ctx context.Context, req *InfoRequest) (*InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (*UnimplementedHospitalDiscoveryServer) ListHospitals(ctx context.Context, req *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHospitals not implemented")
}

func RegisterHospitalDiscoveryServer(s *grpc.Server, srv HospitalDiscoveryServer) {
	s.RegisterService(&_HospitalDiscovery_serviceDesc, srv)
}

func _HospitalDiscovery_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HospitalDiscoveryServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HospitalDiscovery/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HospitalDiscoveryServer).GetInfo(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HospitalDiscovery_ListHospitals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HospitalDiscoveryServer).ListHospitals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HospitalDiscovery/ListHospitals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HospitalDiscoveryServer).ListHospitals(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HospitalDiscovery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HospitalDiscovery",
	HandlerType: (*HospitalDiscoveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _HospitalDiscovery_GetInfo_Handler,
		},
		{
			MethodName: "ListHospitals",
			Handler:    _HospitalDiscovery_ListHospitals_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discovery.proto",
}
